config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get '/' => 'home#index', :as => :home

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
    delete :remove_all
  end

  resource :checkout, only: [:show] do
    get    :show
  end

  resources :orders, only: [:create, :show, :index]

  resources :addresses, only: [:new, :create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, :categories, except: [:edit, :update, :show]
  end

  get '/register' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_filter :require_login

  def add_item
    product_id = params[:product_id].to_s

    item = cart[product_id] || { "quantity" => 0 }
    item["quantity"] += 1
    cart[product_id] = item
    update_cart cart

    redirect_to :back
  end

  def remove_item
    product_id = params[:product_id].to_s

    item = cart[product_id] || { "quantity" => 1 }
    item["quantity"] -= 1
    cart[product_id] = item
    cart.delete(product_id) if item["quantity"] < 1
    update_cart cart

    redirect_to :back
  end

  def remove_all
    update_cart({})

    redirect_to :back
  end

end

app/views/carts/_item.html.erb
<% quantity = details['quantity'].to_i %>

<% if product = Product.find_by(id: product_id) %>
  <% item_total = product.price * quantity %>
  <% @cart_total += item_total %>

  <tr>
    <td>
      <%= image_tag product.image.tiny %>
    </td>
    <td>
      <h4><%= product.name %></h4>
      <br>
      <p><%= product.description %></p>
    </td>
    <td>
      &#8377;<%= product.price %>
    </td>
    <td>
      <%= link_to remove_item_cart_path(product_id: product_id), class: 'btn btn-xs btn-danger', method: :delete do %>
        -
      <% end %>
      <%= quantity %>
      <%= link_to add_item_cart_path(product_id: product_id), class: 'btn btn-xs btn-success', method: :put do %>
        +
      <% end %>
    </td>
    <td>
      &#8377;<%= item_total %>
    </td>
  </tr>
<% end %>

app/views/carts/show.html.erb
<section class="cart-show">

  <header class="page-header">
    <h1>My Cart</h1>
  </header>


  <% if cart.blank? %>

  <div class="alert alert-warning" role="alert">
   Your cart is empty, dawg. Be a good capitalist and buy something!
  </div>

   <% else %>
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @cart_total = 0 %>
        <% cart.each do |product_id, details| %>
          <%= render 'item', product_id: product_id, details: details %>
          <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>
            &#8377;<%= @cart_total %>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="row">
    <div class="col-sm-12  col-md-4">
      <%= button_to "Continue Shopping", root_path , class: "btn btn-block btn-light" , method: :get%>
    </div>
    <% if(cart.count !=0 ) %>
      <div class="col-sm-12  col-md-4">
        <%= button_to "Empty cart", remove_all_cart_path, method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-lg btn-block btn-warning text-uppercase"%>
      </div>
      <div class="col-sm-12 col-md-4 text-right">
        <%= button_to "Checkout", checkout_path , method: :get,class: "btn btn-lg btn-block btn-success text-uppercase"%>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= form_tag orders_path do %>
        <script
          src="https://checkout.razorpay.com/v1/checkout.js" class="stripe-button"
          data-key="<%= ENV['MERCHANT_KEY_ID'] %>"
          data-amount="<%= @cart_total * 100 %>"
          data-name="Intellirio Demo Ecom"
          data-description="<%= current_user.firstname %> <%= current_user.lastname %>'s Order"
          data-prefill.name="<%= "#{current_user.firstname}" %>"
          data-prefill.email="<%= "#{current_user.email}" %>"
          data-theme.color="#F37254">
        </script>
      <% end %>
    </div>
  </div>
  <% end %>

  <br>
  <br>

</section>