config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get '/' => 'home#index', :as => :home

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
    delete :remove_all
  end

  resource :checkout, only: [:show] do
    get    :show
  end

  resources :orders, only: [:create, :show, :index]

  resources :addresses, only: [:new, :create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, :categories, except: [:edit, :update, :show]
  end

  get '/register' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category
  has_many :reviews, -> { order(created_at: :desc) }

  validates_presence_of :name, :price, :quantity, :category


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:success] = "Product created!"
      redirect_to [:admin, :products]
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    flash[:danger] = "Product has been deleted."
    redirect_to [:admin, :products]
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/views/products/_banner.html.erb
<!-- /banner_bottom_agile_info -->
<div class="page-head_agile_info_w3l">
    <div class="container">
        <h3>Men's <span>Wear  </span></h3>
        <!--/w3_short-->
        <div class="services-breadcrumb">
            <div class="agile_inner_breadcrumb">

                <ul class="w3_short">
                    <li><a href="/">Home</a><i>|</i></li>
                    <li>Men's Wear</li>
                </ul>
            </div>
        </div>
        <!--//w3_short-->
    </div>
</div>

<!-- banner-bootom-w3-agileits -->

app/views/products/_bottom_grid.html.erb
<!--/grids-->
<div class="coupons">
    <div class="coupons-grids text-center">
        <div class="w3layouts_mail_grid">
            <div class="col-md-3 w3layouts_mail_grid_left">
                <div class="w3layouts_mail_grid_left1 hvr-radial-out">
                    <i class="fa fa-truck" aria-hidden="true"></i>
                </div>
                <div class="w3layouts_mail_grid_left2">
                    <h3>FREE SHIPPING</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                </div>
            </div>
            <div class="col-md-3 w3layouts_mail_grid_left">
                <div class="w3layouts_mail_grid_left1 hvr-radial-out">
                    <i class="fa fa-headphones" aria-hidden="true"></i>
                </div>
                <div class="w3layouts_mail_grid_left2">
                    <h3>24/7 SUPPORT</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                </div>
            </div>
            <div class="col-md-3 w3layouts_mail_grid_left">
                <div class="w3layouts_mail_grid_left1 hvr-radial-out">
                    <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                </div>
                <div class="w3layouts_mail_grid_left2">
                    <h3>MONEY BACK GUARANTEE</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                </div>
            </div>
            <div class="col-md-3 w3layouts_mail_grid_left">
                <div class="w3layouts_mail_grid_left1 hvr-radial-out">
                    <i class="fa fa-gift" aria-hidden="true"></i>
                </div>
                <div class="w3layouts_mail_grid_left2">
                    <h3>FREE GIFT COUPONS</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!--grids-->

app/views/products/_featured.html.erb
<div class="w3_agile_latest_arrivals">
    <h3 class="wthree_text_info">Featured <span>Arrivals</span></h3>

    <% @products = Product.first(4) %>
    <%= render @products %>
<!--     <div class="col-md-3 product-men single">
        <div class="men-pro-item simpleCart_shelfItem">
            <div class="men-thumb-item">
                <img src="<%= image_url('w2') %>" alt="" class="pro-image-front">
                <img src="<%= image_url('w2') %>" alt="" class="pro-image-back">
                <div class="men-cart-pro">
                    <div class="inner-men-cart-pro">
                        <a href="single.html" class="link-product-add-cart">Quick View</a>
                    </div>
                </div>
                <span class="product-new-top">New</span>

            </div>
            <div class="item-info-product ">
                <h4><a href="single.html">Sleeveless Solid Blue Top</a></h4>
                <div class="info-product-price">
                    <span class="item_price">$140.99</span>
                    <del>$189.71</del>
                </div>
                <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">
                    <form action="#" method="post">
                        <fieldset>
                            <input type="hidden" name="cmd" value="_cart">
                            <input type="hidden" name="add" value="1">
                            <input type="hidden" name="business" value=" ">
                            <input type="hidden" name="item_name" value="Sleeveless Solid Blue Top">
                            <input type="hidden" name="amount" value="30.99">
                            <input type="hidden" name="discount_amount" value="1.00">
                            <input type="hidden" name="currency_code" value="USD">
                            <input type="hidden" name="return" value=" ">
                            <input type="hidden" name="cancel_return" value=" ">
                            <input type="submit" name="submit" value="Add to cart" class="button">
                        </fieldset>
                    </form>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-3 product-men single">
        <div class="men-pro-item simpleCart_shelfItem">
            <div class="men-thumb-item">
                <img src="<%= image_url('w4') %>" alt="" class="pro-image-front">
                <img src="<%= image_url('w4') %>" alt="" class="pro-image-back">
                <div class="men-cart-pro">
                    <div class="inner-men-cart-pro">
                        <a href="single.html" class="link-product-add-cart">Quick View</a>
                    </div>
                </div>
                <span class="product-new-top">New</span>

            </div>
            <div class="item-info-product ">
                <h4><a href="single.html">Black Basic Shorts</a></h4>
                <div class="info-product-price">
                    <span class="item_price">$120.99</span>
                    <del>$189.71</del>
                </div>
                <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">
                    <form action="#" method="post">
                        <fieldset>
                            <input type="hidden" name="cmd" value="_cart">
                            <input type="hidden" name="add" value="1">
                            <input type="hidden" name="business" value=" ">
                            <input type="hidden" name="item_name" value="Black Basic Shorts">
                            <input type="hidden" name="amount" value="30.99">
                            <input type="hidden" name="discount_amount" value="1.00">
                            <input type="hidden" name="currency_code" value="USD">
                            <input type="hidden" name="return" value=" ">
                            <input type="hidden" name="cancel_return" value=" ">
                            <input type="submit" name="submit" value="Add to cart" class="button">
                        </fieldset>
                    </form>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-3 product-men single">
        <div class="men-pro-item simpleCart_shelfItem">
            <div class="men-thumb-item">
                <img src="<%= image_url('s6') %>" alt="" class="pro-image-front">
                <img src="<%= image_url('s6') %>" alt="" class="pro-image-back">
                <div class="men-cart-pro">
                    <div class="inner-men-cart-pro">
                        <a href="single.html" class="link-product-add-cart">Quick View</a>
                    </div>
                </div>
                <span class="product-new-top">New</span>

            </div>
            <div class="item-info-product ">
                <h4><a href="single.html">Aero Canvas Loafers  </a></h4>
                <div class="info-product-price">
                    <span class="item_price">$120.99</span>
                    <del>$199.71</del>
                </div>
                <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">
                    <form action="#" method="post">
                        <fieldset>
                            <input type="hidden" name="cmd" value="_cart">
                            <input type="hidden" name="add" value="1">
                            <input type="hidden" name="business" value=" ">
                            <input type="hidden" name="item_name" value="Aero Canvas Loafers">
                            <input type="hidden" name="amount" value="30.99">
                            <input type="hidden" name="discount_amount" value="1.00">
                            <input type="hidden" name="currency_code" value="USD">
                            <input type="hidden" name="return" value=" ">
                            <input type="hidden" name="cancel_return" value=" ">
                            <input type="submit" name="submit" value="Add to cart" class="button">
                        </fieldset>
                    </form>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-3 product-men single">
        <div class="men-pro-item simpleCart_shelfItem">
            <div class="men-thumb-item">
                <img src="<%= image_url('w7') %>" alt="" class="pro-image-front">
                <img src="<%= image_url('w7') %>" alt="" class="pro-image-back">
                <div class="men-cart-pro">
                    <div class="inner-men-cart-pro">
                        <a href="single.html" class="link-product-add-cart">Quick View</a>
                    </div>
                </div>
                <span class="product-new-top">New</span>

            </div>
            <div class="item-info-product ">
                <h4><a href="single.html">Ankle Length Socks</a></h4>
                <div class="info-product-price">
                    <span class="item_price">$100.99</span>
                    <del>$159.71</del>
                </div>
                <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">
                    <form action="#" method="post">
                        <fieldset>
                            <input type="hidden" name="cmd" value="_cart">
                            <input type="hidden" name="add" value="1">
                            <input type="hidden" name="business" value=" ">
                            <input type="hidden" name="item_name" value="Ankle Length Socks">
                            <input type="hidden" name="amount" value="30.99">
                            <input type="hidden" name="discount_amount" value="1.00">
                            <input type="hidden" name="currency_code" value="USD">
                            <input type="hidden" name="return" value=" ">
                            <input type="hidden" name="cancel_return" value=" ">
                            <input type="submit" name="submit" value="Add to cart" class="button">
                        </fieldset>
                    </form>
                </div>

            </div>
        </div>
    </div> -->
    <div class="clearfix"> </div>
    <!--//slider_owl-->
</div>

app/views/products/_product.html.erb
<!-- <article class="product">
  <header>
    <%= link_to product do %>
    <%= image_tag product.image.thumb, alt: product.name %>
    <h4><%= product.name %></h4>
    <% end %>
  </header>
  <p class="description">
    <%= product.description %>
  </p>
  <footer class="actions">
    <% if product.quantity > 0 %>
      <%= link_to add_item_cart_path(product_id: product.id), class: 'btn btn-primary', method: :put do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
      <% end %>
    <% end %>
    <%= link_to product, class: 'btn btn-default pull-right' do %>
    Details &raquo;
    <% end %>
  </footer>

  <aside class="price">
    <%= humanized_money_with_symbol product.price %>
  </aside>
  <% if product.quantity == 0 %>
  <%= out_of_stock %>
  <% end %>
</article> -->


<div class="col-md-3 product-men">
    <div class="men-pro-item simpleCart_shelfItem">
        <div class="men-thumb-item">
            <!-- <img src="images/m1.jpg" alt="" class="pro-image-front"> -->
            <!-- <img src="images/m1.jpg" alt="" class="pro-image-back"> -->
            <%= image_tag product.image.thumb, alt: product.name, class: "pro-image-front" %>
            <%= image_tag product.image.thumb, alt: product.name, class: "pro-image-back" %>
            <div class="men-cart-pro">
                <div class="inner-men-cart-pro">
                    <%= link_to product, :class=>"link-product-add-cart" do %>
                      Quick View
                    <% end %>
                </div>
            </div>
            <span class="product-new-top">New</span>

        </div>
        <div class="item-info-product ">
            <h4>
              <%= link_to product do %>
                <%= product.name %>
              <% end %>
            </h4>
            <div class="info-product-price">
                <span class="item_price">&#8377;<%= product.price %></span>
                <del>&#8377;<%= product.price %></del>
            </div>
            <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">
                <% if product.quantity > 0 %>
                    <%= link_to add_item_cart_path(product_id: product.id), class: 'button', method: :put do %>
                      ADD TO CART
                    <% end %>
                <% else %>
                  <a href="#" class="button">Out of Stock</a>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/products/_product_banner.html.erb
<!-- /banner_bottom_agile_info -->
<div class="page-head_agile_info_w3l">
    <div class="container">
        
        <h3><%= product.name %></h3>
        <!--/w3_short-->
        <div class="services-breadcrumb">
            <div class="agile_inner_breadcrumb">

                <ul class="w3_short">
                    <li><a href="/">Home</a><i>|</i></li>
                    <li><%= link_to @product.category.name, @product.category %><i>|</i></li>
                    <li><%= @product.name %></li>
                </ul>
            </div>
        </div>
        <!--//w3_short-->
    </div>
</div>

<!-- banner-bootom-w3-agileits -->

app/views/products/show.html.erb
<%= stylesheet_link_tag 'easy-responsive-tabs' %>
<%= javascript_include_tag 'custom-tabs' %>


<%= render 'product_banner' , :product => @product%>

<!-- banner-bootom-w3-agileits -->
<div class="banner-bootom-w3-agileits">
    <div class="container">
        <div class="col-md-4 single-right-left ">
            <div class="grid images_3_of_2">
                <div class="flexslider">

                    <ul class="slides">
                        <li data-thumb="<%= @product.image.url %>">
                            <div class="thumb-image"> <img src="<%= @product.image.url %>" data-imagezoom="true" class="img-responsive"> </div>
                        </li>
                        <li data-thumb="<%= @product.image.url %>">
                            <div class="thumb-image"> <img src="<%= @product.image.url %>" data-imagezoom="true" class="img-responsive"> </div>
                        </li>
                        <li data-thumb="<%= @product.image.url %>">
                            <div class="thumb-image"> <img src="<%= @product.image.url %>" data-imagezoom="true" class="img-responsive"> </div>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-md-8 single-right-left simpleCart_shelfItem">
            <h3><%= @product.name %></h3>
            <p><span class="item_price">&#8377;<%= @product.price %></span> <del>- &#8377;<%= @product.price %></del></p>
            <div class="rating1">
                <span class="starRating">
          <input id="rating5" type="radio" name="rating" value="5">
          <label for="rating5">5</label>
          <input id="rating4" type="radio" name="rating" value="4">
          <label for="rating4">4</label>
          <input id="rating3" type="radio" name="rating" value="3" checked="">
          <label for="rating3">3</label>
          <input id="rating2" type="radio" name="rating" value="2">
          <label for="rating2">2</label>
          <input id="rating1" type="radio" name="rating" value="1">
          <label for="rating1">1</label>
        </span>
            </div>
            <div class="description">
                <h5>Check delivery, payment options and charges at your location</h5>
                <form action="#" method="post">
                    <input type="text" value="Enter pincode" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter pincode';}" required="">
                    <input type="submit" value="Check">
                </form>
            </div>
            <div class="color-quality">
                <div class="color-quality-right">
                    <h5>Quality :</h5>
                    <select id="country1" onchange="change_country(this.value)" class="frm-field required sect">
                        <option value="1">1 Qty</option>
                        <option value="2">2 Qty</option>
                        <option value="3">3 Qty</option>
                        <option value="4">4 Qty</option>
                        <option value="5">5 Qty</option>
                    </select>
                </div>
            </div>
            <!-- <div class="occasional">
                <h5>Types :</h5>
                <div class="colr ert">
                    <label class="radio">
                        <input type="radio" name="radio" checked=""><i></i>Casual Shoes</label>
                </div>
                <div class="colr">
                    <label class="radio">
                        <input type="radio" name="radio"><i></i>Sneakers </label>
                </div>
                <div class="colr">
                    <label class="radio">
                        <input type="radio" name="radio"><i></i>Formal Shoes</label>
                </div>
                <div class="clearfix"> </div>
            </div> -->
            <div class="occasion-cart">
                <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">
                    <%= link_to add_item_cart_path(product_id: @product.id), class: 'button', method: :put do %>
                      ADD TO CART
                    <% end %>
                </div>

            </div>
            <ul class="social-nav model-3d-0 footer-social w3_agile_social single_page_w3ls">
                <li class="share">Share On : </li>
                <li>
                    <a href="#" class="facebook">
                        <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                    </a>
                </li>
                <li>
                    <a href="#" class="twitter">
                        <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                    </a>
                </li>
                <li>
                    <a href="#" class="instagram">
                        <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                    </a>
                </li>
                <li>
                    <a href="#" class="pinterest">
                        <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                    </a>
                </li>
            </ul>

        </div>
        <div class="clearfix"> </div>
        <!-- /new_arrivals -->
        <div class="responsive_tabs_agileits">
            <div id="horizontalTab">
                <ul class="resp-tabs-list">
                    <li>Description</li>
                    <li>Reviews</li>
                    <li>Information</li>
                </ul>
                <div class="resp-tabs-container">
                    <!--/tab_one-->
                    <div class="tab1">

                        <div class="single_page_agile_its_w3ls">
                            <h6><%= @product.name %></h6>
                            <p><%= @product.description %></p>
                        </div>
                    </div>
                    <!--//tab_one-->
                    <div class="tab2">

                        <div class="single_page_agile_its_w3ls">
                            <div class="bootstrap-tab-text-grids">
                                <% if @product.reviews.count > 0 %>
                                  <h6>Top customer reviews</h6>
                                <% else %>
                                  <h6>Be the first to submit review</h6>
                                <% end %>
                                <% @product.reviews.each do |i| %>
                                  <dt><%= show_stars i.rating %></dt>
                                  <dd>
                                    <%= i.description %>
                                    <br>
                                    Review submitted <%= i.created_at.strftime("%d %B %Y") %>
                                    <br>
                                    <% if i.user == current_user %>
                                      <%= link_to "DELETE REVIEW",
                                          product_review_path(@product, i),
                                          :method => :delete,
                                          class: "btn btn-danger"
                                          %>
                                    <% end %>
                                  </dd>
                                  <br>
                                <% end %>
                                <div class="add-review">
                                    <% if current_user %>
                                      <%= form_for(Review.new, url: product_reviews_path(@product, @review)) do |f| %>
                                      <dt>Add a Review</dt>
                                      <dd><%= f.text_area :description, class: "form-control" %></dd>
                                      <br>
                                      <dt>Rating</dt>
                                      <dd>
                                        <%= f.select :rating,
                                            options_for_select(
                                            [['Excellent', 5],
                                            ['Good', 4],
                                            ['Average', 3],
                                            ['Could be improved', 2],
                                            ['Poor', 1]]),
                                            class: "form-control" %>
                                      </dd>
                                      <br>
                                      <dd><%= f.submit "Submit Review", class: "btn btn-primary" %></dd>
                                      <% end %>
                                    <% end %>
                                    <br>
                                    
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="tab3">

                        <div class="single_page_agile_its_w3ls">
                            <h6><%= @product.name %></h6>
                            <p><%= @product.description %></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- //new_arrivals -->
        <!--/slider_owl-->
        <%=render "featured" %>
    </div>
</div>

<!-- <section class="products-show">

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @product.name %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.quantity %></dd>
          <dt>Price</dt>
          <dd>$ <%= @product.price %></dd>
        </dl>
      </div>
      <div class="col-sm-8">
        <br>
        <dl class="dl-horizontal">
          <% if current_user %>
            <%= form_for(Review.new, url: product_reviews_path(@product, @review)) do |f| %>
            <dt>Add a Review</dt>
            <dd><%= f.text_area :description, class: "form-control" %></dd>
            <br>
            <dt>Rating</dt>
            <dd>
              <%= f.select :rating,
                  options_for_select(
                  [['Excellent', 5],
                  ['Good', 4],
                  ['Average', 3],
                  ['Could be improved', 2],
                  ['Poor', 1]]),
                  class: "form-control" %>
            </dd>
            <br>
            <dd><%= f.submit "Submit Review", class: "btn btn-primary" %></dd>
            <% end %>
          <% end %>
          <br>
          <% @product.reviews.each do |i| %>
          <dt><%= show_stars i.rating %></dt>
          <dd>
            <%= i.description %>
            <br>
            Review submitted <%= i.created_at.strftime("%d %B %Y") %>
            <br>
            <% if i.user == current_user %>
              <%= link_to "DELETE REVIEW",
                  product_review_path(@product, i),
                  :method => :delete,
                  class: "btn btn-danger"
                  %>
            <% end %>
          </dd>
          <br>
          <% end %>
        </dl>
      </div>
    </div>

  </article>

</section> -->

<%=render 'bottom_grid' %>